### ISSUE TITLE
Reproducing PLDI'20 experimental results on two benchmarks

### ISSUE THREAD

**Issue by yicheng-dev** [utopia-group/regel#10]
Dear authors, I am working on a research topic and I may need to use Regel in this new topic. I came across a intractable problem (may be my operation problems) when I attempted to call interactive.py on benchmark DeepRegex and SO for running experiments to check whether the actual results match the results shown in PLDI'20.

Specificly, after I prepared the required libraries of this repo, I entered:

```
python3 interactive.py --run_mode 1
```

Then I found that when Regel was synthesizing for the #62 and #50 (may be more) of benchmark DeepRegex, it reminded me to input two additional examples. According to my understanding, it means the examples already in the benchmark #62 and `exp/interactive/deepregex/examples_cache/` are still not enough for synthesizing/distinguishing a final solution. I re-read the paper but found no more hints for it. So when running this controlled experiments, is it necessary for users to manually provide more examples so that one could finally obtain the overall results and compare it with experimental results in the PLDI'20 paper?

If it is convenient for you, please give a brief tutorial for guiding me (also other researchers) how to run the experiments correctly and quickly to get the experimental results in the PLDI'20 paper. Thank you very much!

**Comment by yicheng-dev** [comment]
In addition, if it is necessary for us to manually provide more examples in this interative mode to get the overall experimental results, could you provide the corresponding additional examples when you performed the experiments and then got the results in Fig. 14 (PLDI'20)? Thanks! If it is not convenient, I want to know if it is a heavy work to write these additional positive/negative examples.

**Comment by thelyad** [comment]
I think now at least #62 and #50 should work correctly. Please see the most recent commits.

> it means the examples already in benchmark #62 and exp/interactive/deepregex/examples_cache/

The examples in this folder are not guaranteed to be sufficient for the interactive mode to work without user inputs. I tried to keep the examples I used but it might not be the version that I used for the evaluation.

> If it is convenient for you, please give a brief tutorial for guiding me (also other researchers) how to run the experiments correctly and quickly to get the experimental results in the PLDI'20 paper. 

Unfortunately, I do not have the examples I used for producing Fig. 14. I would say that using whatever in the examples_cache should be the best try. Also, this code is the released version of the tool which might be different from the code I used for evaluation. The enumeration order might be different so you may need different examples. I haven't actually tried this version to reproduce the evaluation but I think it should be close. 

> I want to know if it is a heavy work to write these additional positive/negative examples.

It does require you to understand the DSL and interpret the natural language as intended and in some case some iteration of interaction. But overall imo it shouldn't be that hard.

**Comment by yicheng-dev** [comment]
Thank you for your answers, I will try again.
