### ISSUE TITLE
getting missing sketch error when sketches are found in regel/exp/deepregex/sketch

### ISSUE THREAD

**Issue by wailoktam** [utopia-group/regel#8]
Hi, I run the following command under the regel folder:

 python3 exp.py --benchmark deepregex --sketch  /regel/exp/deepregex/sketch --synth_mode 1 --processnum 1          

after running           

python3 parse_benchmarks.py --benchmark deepregex --model_dir pretrained_models/pretrained_turk --max_sketch 1

**Comment by thelyad** [comment]
Can you provide some error log files so I can take a look at them?
