### ISSUE TITLE
automatic conversion of the target regex

### ISSUE THREAD

**Issue by wailoktam** [utopia-group/regel#9]
I am wondering whether you have any code yourself or know of any library that convert the regex language you use into any form actually used by a programming language. I suppose you have something to check whether the generated regex in your regex language would accept a positive example and reject a negative example during evaluation. Can you direct me to the relevant part? Thanks.

**Comment by thelyad** [comment]
I believe the getRegex function in PartialProgram.java can convert the program in our DSL to a regex that can be accepted by the Automaton library. You can you that library to check whether its consistency with the examples.

**Comment by wailoktam** [comment]
Thanks. Instead of supplying examples to check whether a sketch would match (I believe this needs the example needs to be a full match with nothing extra), I want to supply examples and get the sketch to extract the portion that matches the sketch. Can you highlight the part of the codes that is relevant to making this possible? Thanks.

**Comment by YuanWangC** [comment]
Excuse me, I am trying to generate executable regular expressions using Regel, could you please tell me how to call PartialProgram.java to get executable regular expressions after calling exp.py and process_output.py with commands? @thelyad

**Comment by thelyad** [comment]
@wailoktam The current code actually does not support this feature. I think this might be difficult since there probably does not exist a 1 to 1 mapping between the sketch and part of the strings that match parts of the sketch.

**Comment by thelyad** [comment]
@YuanWangC You should be able to obtain the executable regex in the exp.py now #11 . I also output all the synthesized results in a csv format located in $your_log_path/all_results.csv. In this case, you probably don't have to call process_output.py #12 .
